name: Dry run Github Pages

on:
  pull_request:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install website packages
        run: |
          gem --version
          sudo gem install bundler
          npm install -g npm@9.2.0
          npm install --no-audit
          sudo npm run install-jekyll

      - uses: helaili/jekyll-action@v2
        with:
          build_only: true
          gem_src: site
