name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install website packages
        run: |
          gem --version
          sudo gem install bundler
          npm install --no-audit
          npm run install-jekyll

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          gem_src: site
          target_branch: gh-pages
